apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epi-search
  template:
    metadata:
      labels:
        app: epi-search
    spec:
      containers:
      - name: epi-search
        image: ghcr.io/gravitate-health/epi-search
        env:
        - name: FHIR_URL
          value: "http://fhir-server-epi:8080/api/fhir/Bundle?_format=json"
        ports:
        - containerPort: 3000